const std = @import("std");

pub const intrinsic_id = enum {
    iadd,
    isub,
    imul,
    idiv,
    irem,
    imin,
    imax,
    ieq,
    ine,
    ilt,
    ile,
    igt,
    ige,
    ineg,
    iabs,
    bnot,
    band,
    bor,
    bxor,
    shl,
    shr,
    sar,
    rol,
    ror,

    fadd,
    fsub,
    fmul,
    fdiv,
    frem,
    fmin,
    fmax,
    feq,
    fne,
    flt,
    fle,
    fgt,
    fge,
    fneg,
    fabs,
    sqrt,
    sin,
    cos,
    tan,
    asin,
    acos,
    atan,
    floor,
    ceil,
    round,
    trunc,
    alloc,
    free,
    deref,
    type_words,
    result_ok,
    result_err,
    result_is_ok,
    result_unwrap,
    result_unwrap_err,
    interpolate,
};

pub const intrinsic_def = struct {
    name: []const u8,
    id: intrinsic_id,
    arity: u8,
    variadic: bool = false,
};

const intrinsics = [_]intrinsic_def{
    .{ .name = "iadd", .id = .iadd, .arity = 2 },
    .{ .name = "isub", .id = .isub, .arity = 2 },
    .{ .name = "imul", .id = .imul, .arity = 2 },
    .{ .name = "idiv", .id = .idiv, .arity = 2 },
    .{ .name = "irem", .id = .irem, .arity = 2 },
    .{ .name = "imin", .id = .imin, .arity = 2 },
    .{ .name = "imax", .id = .imax, .arity = 2 },
    .{ .name = "ieq", .id = .ieq, .arity = 2 },
    .{ .name = "ine", .id = .ine, .arity = 2 },
    .{ .name = "ilt", .id = .ilt, .arity = 2 },
    .{ .name = "ile", .id = .ile, .arity = 2 },
    .{ .name = "igt", .id = .igt, .arity = 2 },
    .{ .name = "ige", .id = .ige, .arity = 2 },
    .{ .name = "ineg", .id = .ineg, .arity = 1 },
    .{ .name = "iabs", .id = .iabs, .arity = 1 },
    .{ .name = "bnot", .id = .bnot, .arity = 1 },
    .{ .name = "band", .id = .band, .arity = 2 },
    .{ .name = "bor", .id = .bor, .arity = 2 },
    .{ .name = "bxor", .id = .bxor, .arity = 2 },
    .{ .name = "shl", .id = .shl, .arity = 2 },
    .{ .name = "shr", .id = .shr, .arity = 2 },
    .{ .name = "sar", .id = .sar, .arity = 2 },
    .{ .name = "rol", .id = .rol, .arity = 2 },
    .{ .name = "ror", .id = .ror, .arity = 2 },

    .{ .name = "fadd", .id = .fadd, .arity = 2 },
    .{ .name = "fsub", .id = .fsub, .arity = 2 },
    .{ .name = "fmul", .id = .fmul, .arity = 2 },
    .{ .name = "fdiv", .id = .fdiv, .arity = 2 },
    .{ .name = "frem", .id = .frem, .arity = 2 },
    .{ .name = "fmin", .id = .fmin, .arity = 2 },
    .{ .name = "fmax", .id = .fmax, .arity = 2 },
    .{ .name = "feq", .id = .feq, .arity = 2 },
    .{ .name = "fne", .id = .fne, .arity = 2 },
    .{ .name = "flt", .id = .flt, .arity = 2 },
    .{ .name = "fle", .id = .fle, .arity = 2 },
    .{ .name = "fgt", .id = .fgt, .arity = 2 },
    .{ .name = "fge", .id = .fge, .arity = 2 },
    .{ .name = "fneg", .id = .fneg, .arity = 1 },
    .{ .name = "fabs", .id = .fabs, .arity = 1 },
    .{ .name = "sqrt", .id = .sqrt, .arity = 1 },
    .{ .name = "sin", .id = .sin, .arity = 1 },
    .{ .name = "cos", .id = .cos, .arity = 1 },
    .{ .name = "tan", .id = .tan, .arity = 1 },
    .{ .name = "asin", .id = .asin, .arity = 1 },
    .{ .name = "acos", .id = .acos, .arity = 1 },
    .{ .name = "atan", .id = .atan, .arity = 1 },
    .{ .name = "floor", .id = .floor, .arity = 1 },
    .{ .name = "ceil", .id = .ceil, .arity = 1 },
    .{ .name = "round", .id = .round, .arity = 1 },
    .{ .name = "trunc", .id = .trunc, .arity = 1 },
    .{ .name = "alloc", .id = .alloc, .arity = 1 },
    .{ .name = "free", .id = .free, .arity = 1 },
    .{ .name = "deref", .id = .deref, .arity = 1 },
    .{ .name = "type_words", .id = .type_words, .arity = 1 },
    .{ .name = "result_ok", .id = .result_ok, .arity = 1 },
    .{ .name = "result_err", .id = .result_err, .arity = 1 },
    .{ .name = "result_is_ok", .id = .result_is_ok, .arity = 1 },
    .{ .name = "result_unwrap", .id = .result_unwrap, .arity = 1 },
    .{ .name = "result_unwrap_err", .id = .result_unwrap_err, .arity = 1 },
    .{ .name = "interpolate", .id = .interpolate, .arity = 0, .variadic = true },
};

pub fn lookup(name: []const u8) ?intrinsic_def {
    for (intrinsics) |item| {
        if (std.mem.eql(u8, item.name, name)) return item;
    }
    return null;
}

pub fn names() []const intrinsic_def {
    return intrinsics[0..];
}
