[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pygments-ink"
version = "0.1.0"
description = "Ink lexer for Pygments"
requires-python = ">=3.8"
dependencies = ["pygments"]

[project.entry-points."pygments.lexers"]
ink = "pygments_ink:InkLexer"
